<footer>
		<div class="container">
			<div class="flex">
				<aside class="cours">
					<h4>Activités proposé</h4>
					<ul>
						<li>Danse Enfants - Mercredi: 15h30 - 16h30 </li>
						<li>Danse Adultes - Vendredi : 19h30 - 20h30</li>
						<li>Ukulele - Vendredi : 20h30 - 21h30 (selon disponibilité)</li>
						<li>Ateliers Tressage - Samedi : 14h30 - 16h45 (3ème samedi du mois)</li>
					</ul>
				</aside>
				<aside>
					<h4>Contact</h4>
					<address>
						<p>Maison des Associations<br>
							2bis Av. Albert de Mun,
						</p>
						<ul>
							<li><i class="fas fa-phone-volume"></i> +33 8100 3429</li>
		                    <li><i class="fas fa-at"></i>asso.rimahere@gmail.com</li>
		                    <li><i class="fas fa-map-marker-alt"></i> Saint-Nazaire, 44 600 - Pays de la Loire</li>
	                    </ul>
					</address>
				</aside>
				<aside>
					<h4>Réseaux sociaux</h4>
					<div class="reseaux">
						<a href="https://www.facebook.com/rimaheresaintnazaire" ><i class="fab fa-facebook-f" blank="#"></i></a>
						<a href="https://www.instagram.com/rimaheresaintnazaire"><i class="fab fa-instagram" blank="#"></i></a>
						<a href="https://www.tiktok.com/@rima_here_saint_nazaire" ><i class="fa-brands fa-tiktok" blank="#"></i></a>
					</div>
				</aside>
			</div>
		</div>
	</footer>
        <script src="js/scripts.js"></script>
</body>
</html>