<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="site vitrine de l'association RimaHere de Saint-Nazaire">
    <title>L'Association RimaHere Saint-Nazaire</title>
    <link rel="stylesheet" href="<?=$base_uri[0] ?>/public/assets/front/css/style.css" type="text/css"/>

    <link rel="icon" type="image/x-icon" href="<?= $base_uri[0].'/public/assets/front/favicon.ico' ?>"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    
</head>

<body>
    <header>
        <div class="nav-container">
        <a href="index.html"><img src="<?=$base_uri[0] ?>/public/assets/front/favicon.ico" alt="Logo de l'association" id="logo">
        </a>
        <nav>
            <ul>
            <li><a href="<?=$base_uri[0] ?>/public/home">Accueil</a></li>
            <li><a href="<?=$base_uri[0] ?>/public/about">A Propos</a></li>
            <li><a href="<?=$base_uri[0] ?>/public/activities">Activités</a></li>
            <li><a href="<?=$base_uri[0] ?>/public/contact">Contact</a></li>
            <li><a href="<?=$base_uri[0] ?>/public/register">Inscription</a></li>
            <li><a href="<?=$base_uri[0] ?>/public/login">Connexion</a></li>
            </ul>
        </nav>
    </div>
        <h1>L'Association RimaHere Saint-Nazaire</h1>
</header>

