<style type="text/css">
    
</style>

<h1>Je suis bien la page administration</h1>

<div class="container">
<a href="#" class="btn-add">Ajouter</a>
<table class="table">
    <tr id="items">
        <td>Date</td>
        <td>Name</td>
        <td>Description</td>
        <td>Niveau</td>
        <td>Identifiant</td>
        <td>Modifier</td>
        <td>Supprimer</td>
    </tr>
    <tr>
        <td>getDate</td>
        <td>getName</td>
        <td>getDescription</td>
        <td><i class="fa-solid fa-pen"><a href="#">Modifier</a></i></td>
        <td>SUPPRIMER</td>
    </tr>
</table>



</div>