<h2>A propos</h2>

<h3>Bienvenue sur le site de l'Association RIMAHERE Saint-Nazaire !</h3>

<p>Nous sommes ravis de vous accueillir au cœur de notre univers dédié à la pirogue polynésienne et à sa culture fascinante.</p>

<h4>Notre Origine et Notre Passion</h4>

L'association RIMAHERE Saint-Nazaire est née d'une idée commune, partagée par un groupe d'amis profondément épris d'un sport qui incarne à la fois l'aventure, la connexion à la nature et le respect des traditions : la pirogue polynésienne. Nous avons uni nos forces et notre enthousiasme pour créer une communauté passionnée qui célèbre non seulement l'art de la pirogue, mais également la richesse de la culture polynésienne qui l'accompagne.

<h4>La Pirogue Polynésienne : Un Art, un Mode de Vie</h4>

Au cœur de notre association se trouve l'amour pour la pirogue polynésienne, un mode de navigation ancestral empreint de respect pour l'océan et l'environnement. Nous explorons ensemble les eaux marines, naviguons en harmonie avec les vagues et partageons des moments inoubliables au sein de notre équipage. Plus qu'un simple sport, la pirogue est pour nous un moyen de nous connecter à la nature et de puiser dans les traditions maritimes anciennes.

<h4>La Culture Polynésienne : Une Source d'Inspiration</h4>

La pirogue polynésienne ne vient pas seule, elle est accompagnée d'une culture riche et vibrante. Nous célébrons la musique, la danse, l'artisanat et les coutumes qui ont façonné la Polynésie. Notre association organise des événements culturels, des ateliers d'artisanat et des séances de danse traditionnelle pour partager l'héritage de ces îles magnifiques avec notre communauté.

<h4>Notre Objectif</h4>

L'Association RIMAHERE Saint-Nazaire a pour vocation de rassembler les âmes passionnées par la pirogue polynésienne et son univers culturel. Nous souhaitons créer un espace où les amitiés se tissent, les connaissances se partagent et les aventures maritimes prennent vie. Que vous soyez un navigateur aguerri ou simplement curieux d'en apprendre davantage sur la culture polynésienne, vous êtes les bienvenus au sein de notre famille.

Nous vous invitons à explorer notre site pour en savoir plus sur nos activités, nos événements à venir et les ressources que nous mettons à votre disposition. Rejoignez-nous dans cette aventure passionnante à la découverte de la pirogue polynésienne et de son héritage culturel exceptionnel.

N'hésitez pas à nous contacter pour toute question ou pour en savoir plus sur la manière de devenir membre de l'Association RIMAHERE Saint-Nazaire.

<img src="<?=$base_uri[0] ?>/public/assets/front/img/home.jpg" alt="Logo de l'association" id="logo">LAssociation au Jardin des Plantes de Saint-Nazaire</img>