<p>Ceci est une Activity</p>
<?php foreach($data as $activity): ?>
<div class="card">
    <h1><?= $activity->getName(); ?></h1>
    <small><?= $activity->getDate(); ?></small>
    <p><?= $activity->getContent(); ?></p>
    <iframe src="https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2FVendeeVaa%2Fvideos%2F1324759935064651%2F&show_text=false&width=560&t=0" width="560" height="314" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" allowFullScreen="true"></iframe>
    </div>
<?php endforeach; ?>
