<main>
    <div class="container-bg-video">
        <video id="background-video" autoplay loop muted>
        <source src="https://assets.codepen.io/6093409/river.mp4" type="video/mp4">
        </video>
        <div class="content">
            <h1>BIEN PLUS QU'UNE RIVIÈRE</h1>
            <h2>Une source de vie</h2>
        </div>
    </div>
    <div class="container">
    <section class="about-us">
        <article class="us">
            <img src="<?=$base_uri[0] ?>/public/assets/front/img/img/ori.jpg" class="ori" alt="Danseuse"></img>
            <div class="apropos">
            <h3>A propos</h3>
            <p>Bienvenue sur le site de l'Association RIMAHERE Saint-Nazaire ! Plongez dans la Polynésie à travers nos activités envoûtantes : de la danse Ori Tahiti à la pirogue Vaa, du tressage Rara'a au ukulélé. Explorez ces trésors culturels uniques et partagez une aventure inoubliable avec nous.</p>
            </div>
        </article>
    </section>