<!-- Main Content-->

<main class="container">
    <form action="" method="post">
        <label for="email">Votre email</label>
        <input type="text" name="email" id="email"/>
        <label for="password">Votre password</label>
        <input type="password" name="password" id="password"/>
        <input type="submit" value="Envoyer" name="loginForm"/>
    </form>
</main> 
<div>
    <?php if (isset($data)) {
        foreach ($data as $value) {
            echo $value;
        }
    } ?>
</div>