<!-- Main Content-->

<main class="container">
    <form action="" method="post">
        <label for="email">Votre email</label>
        <input type="text" name="email" id="email"/>
        <label for="password">Votre password</label>
        <input type="text" name="password" id="password"/>
        <input type="submit" value="Envoyer" name="loginForm" onclick="myFunction"/>
    </form>
</main> 
<?php foreach($data as $message){
    echo $message;
}?>